version: "3.3"
services:
  backend:
    build: .
    ports: ["8000:8000"]
    environment:
      - OCR_URL=http://ocr:9002
      - LLM_URL=http://llm:9003
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on: [db, redis, ocr, llm]
  ocr:
    build: ./services/ocr
    ports: ["9002:9002"]
  llm:
    build: ./services/llm
    ports: ["9003:9003"]
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports: ["5432:5432"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
